version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"